language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get -t -v ./...

script:
  - go test -covermode=count -coverprofile=profile.cov
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
